# Generated by Django 5.1.7 on 2025-04-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PW_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedpassword',
            name='created_at',
        ),
    ]
