# Generated by Django 5.1.7 on 2025-04-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PW_app', '0002_remove_savedpassword_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpassword',
            name='username',
            field=models.CharField(default='default_username', max_length=100),
        ),
    ]
